### ISSUE TITLE
Homepage Optimization + Polishing

### ISSUE THREAD

**Issue by aaroncox** [greymass/unicove#310]
The homepage elements are visible now with Debug Mode enabled in the settings.

We should do a pass on these components to optimize for mobile as well as clean up the code to match designs.

A list of things I've observed, but is by no means a complete list:

- [x] Implement redesigned header element per Max in design channel. No link/cta though. Hide element when logged in?
- [x] Remove the two elements for "Early Access" and "Still looking for v1?"
- [x] Link the "Learn more" on staking to https://eosnetwork.com/staking-rewards/ (until we have a page like this)
- [x] Cleanup and match the EOS and RAM chart elements to the designs. Align content below them. Potentially shrink height of charts to fit more with content.
- [x] Design pass on the tile metrics towards the bottom for sizing, organization, etc

**Comment by deansallinen** [comment]
I don't think we should hide the hero when logged in. At least not until we have a full dashboard of data.
